vanderbilt-redcap/dashboard-analysis-platform

- classes/Crons.php
I didn't push this as I'm in no rush as it's by the end of the day but if not I'll do what we talked and push it to prod directly
> Adding error logs

- classes/Crons.php
- classes/ProjectData.php
- config.json
- dashboard_cache.php
- graph_ajax.php
If version is greater than 13.11.3 specify file name differently.
New path variable to be able to save the documents in a different spot than EDOCS.
Removed extra copy generated by storeFile and moved path to TEMP.
> Save file with name if version is greater than 13.11.3

- classes/Crons.php
Found a possible vulnerability issue.
Omitting the rest from the scan as they are related to the S3 changes. Just so you are aware later on when I create the repo version.
> vulnerability fix

- classes/CronData.php
- classes/Crons.php
- classes/GraphData.php
- classes/ProjectData.php
- classes/R4Report.php
- classes/REDCapCalculations.php
- config.json
- dashboard_cache.php
Overall change is that getData calls have been replaced with R4Report::applyFilterLogicToData which applies the filtering logic to the data and only pulls the data once.
I tested this on a subset of ~500 records from one of the EPV projects and the output is the same.
> Kyle speedup take2

- classes/ProjectData.php
New changes we discussed. I tested them and it works well.
> New validateDomainSuffix addition

- classes/CronData.php
- classes/Crons.php
- classes/GraphData.php
- classes/ProjectData.php
- config.json
- dashboard_cache.php
> Dashboard fixes

- DashboardAnalysisPlatformExternalModule.php
- classes/Crons.php
- classes/ProjectData.php
> vulnerabilities

- classes/Crons.php
- classes/GraphData.php
- dashboard_cache.php
- graph_ajax.php
- Added extra data (responses_na) to the graphs file.
- Fixed Ethnicity option not being checked.
- Added JS code to display the data on hover window.
> Graph labels records

- classes/GraphData.php
- graph_ajax.php
- Unified code in functions to do not repeat unnecessarily
- Added no tops calculations
- New chart logic:  if n=0 and %=0 do not show a point in the graph but if n has a value show it even if it's % is 0
> Fixes on Graph File

- classes/GraphData.php
Quick fix to check the keys in the arrays.
> fixed to check the key

- classes/CronData.php
- classes/Crons.php
- classes/ProjectData.php
- dashboard_cache.php
- Modified custom filters to display name
- Bug fix on string. Changed all comparison conditionals to ensure it compares agains empty string and not boolean.
> Quick bugs fixes and changes

- classes/CronData.php
- classes/Crons.php
- classes/GraphData.php
- classes/ProjectData.php
- classes/R4Report.php
- dashboard_cache.php
- graph_ajax.php
I went ahead and created the pull request as this week is the last week they have budget for it and I would like to be able to add this on production.
There might be more changes coming but I think they won't be as big as this one. I wanted to make sure there was enough time to review. Better do the big one with time and any smaller ones later :)
- Added By Site graph:
- New function and variable to get Institution Data.
- Fixed error on custom filters not showing hover.
- Arranged data in functions
- New constant for custom filters
> Code improvements

- classes/CronData.php
- classes/Crons.php
- classes/GraphData.php
- classes/ProjectData.php
- classes/R4Report.php
- dashboard_cache.php
- graph_ajax.php
- response_rates_selector_ajax.php
Clean up of functions and adding constants.
Also a minor bug fix on chart display.
> Data improvements

- classes/GraphData.php
- dashboard_cache.php
- Chart issue with by site
- Condition changed for No Reported option on graph.
> Bug fixes (quick)

- classes/GraphData.php
- classes/ProjectData.php
- dashboard_cache.php
Bug fix. Code might not be the prettiest but trying to have this working asap
> bug fix on multiple graph

- .idea/.gitignore
- .idea/codeStyles/codeStyleConfig.xml
- .idea/dashboard-analysis-platform_v1.0.0.iml
- .idea/modules.xml
- .idea/vcs.xml
- DashboardAnalysisPlatformExternalModule.php
- head_scripts.php
Updated jquery following guidelines.
> Updated jQuery

- classes/ProjectData.php
There's an issue where it seems some array keys are not found
Splunk message:
2/5/256:57:30.000 AM | Error message: Warning - Undefined array key "race___10116", File: /app001/www/redcap/modules/dashboard-analysis-platform_v1.35/classes/ProjectData.php, Line: 348host = ori1123lpsource = /app001/www-logs/redcap_cron_logsourcetype = victr_cron_log
-- | --
> check if the key exists

- classes/ProjectData.php
Added new variable to the list.
New variable needs to be added to the table.
> new question added

- classes/Crons.php
- config.json
Changed paths and saving methods to be able to use REDCap's AWS method.
Rockefeller is using REDCap's AWS to save files instead of the usual server making the way we save files not work properly for them. This fixes this issue adding an option to activate this setting through the configuration.
> Rockefeller aws changes

- classes/Crons.php
Added some error checks.
REDCap sent some error logs on something failing when saving the file. Added some error checks.
> added some error checks
